### ISSUE TITLE
What about exactly 4 times?

### ISSUE THREAD

**Issue by akond** [AbhinavOmprakash/luna#1]
How do I describe this regexp `\d{4}`?
I would expect to find something like `:digits :exactly 4 :times`.

**Comment by AbhinavOmprakash** [comment]
Hey, thanks for bringing this up. I will add this and push a release.

**Comment by AbhinavOmprakash** [comment]
fixed and created a release. please see !

**Comment by akond** [comment]
Yes, that fixes it.

**Comment by AbhinavOmprakash** [comment]
I’m curious do you actually use this in a project or were you just playing around with it?

**Comment by akond** [comment]
I was about to, but I could not do what I wanted (I don't remember what it was), so I switched to `net.cgrand/regex`, which did the trick.

**Comment by AbhinavOmprakash** [comment]
Oh I see. cgrand’s library is quite mature. If you remember what you were trying to do, please open up an issue :)
